# Generated by Django 3.0.11 on 2021-09-12 01:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentID', models.CharField(max_length=6)),
                ('departmentName', models.CharField(max_length=21)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link_dir', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=120)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='JenisBerkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenisCode', models.CharField(max_length=6)),
                ('jenisName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleCode', models.CharField(max_length=4)),
                ('roleName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBerkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCode', models.CharField(max_length=3)),
                ('typeName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.ManyToManyField(blank=True, to='user.Department')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BerkasMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=120, null=True)),
                ('address_sender', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('all_approve', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('approve_manager', models.ManyToManyField(blank=True, related_name='manager', to='user.Pengguna')),
                ('approve_staff', models.ManyToManyField(blank=True, related_name='staff', to='user.Pengguna')),
                ('jenisBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.JenisBerkas')),
                ('linked_file', models.ManyToManyField(blank=True, to='user.File')),
                ('typeBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TypeBerkas')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pengguna')),
                ('upload_for', models.ManyToManyField(to='user.Role')),
                ('upload_to_departement', models.ManyToManyField(to='user.Department')),
            ],
        ),
        migrations.CreateModel(
            name='BerkasKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=120, null=True)),
                ('address_destination', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('jenisBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.JenisBerkas')),
                ('linked_file', models.ManyToManyField(blank=True, to='user.File')),
                ('typeBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TypeBerkas')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Pengguna')),
                ('upload_from_departement', models.ManyToManyField(to='user.Department')),
            ],
        ),
    ]
