# Generated by Django 3.0.11 on 2021-09-14 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departementID', models.CharField(max_length=6)),
                ('departementName', models.CharField(max_length=21)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=40, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisiID', models.CharField(max_length=6)),
                ('divisiName', models.CharField(max_length=21)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=40, null=True)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arsip.Department')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisBerkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenisCode', models.CharField(max_length=6)),
                ('jenisName', models.CharField(max_length=16)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=21)),
                ('password', models.TextField(max_length=21)),
                ('nik', models.TextField(blank=True, max_length=60)),
                ('qr_code', models.IntegerField()),
                ('time_login', models.IntegerField(default=5000)),
                ('cookies', models.TextField(blank=True, max_length=21)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ManyToManyField(to='arsip.Department')),
                ('divisi', models.ManyToManyField(to='arsip.Divisi')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleCode', models.CharField(max_length=4)),
                ('roleName', models.CharField(max_length=16)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default=None, max_length=120)),
                ('typeBerkas', models.CharField(choices=[('B', 'Biasa'), ('P', 'Penting'), ('SP', 'Sangat Penting')], default='B', max_length=10)),
                ('address_sender', models.CharField(max_length=160, null=True)),
                ('sender', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('approve_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved', to='arsip.Pengguna')),
                ('department', models.ManyToManyField(to='arsip.Department')),
                ('file', models.ManyToManyField(to='arsip.File')),
                ('jenisBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arsip.JenisBerkas')),
                ('reader', models.ManyToManyField(blank=True, related_name='reader', to='arsip.Pengguna')),
                ('signature', models.ManyToManyField(blank=True, related_name='signature', to='arsip.Pengguna')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded', to='arsip.Pengguna')),
                ('upload_for', models.ManyToManyField(related_name='target', to='arsip.Pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default=None, max_length=120)),
                ('typeBerkas', models.CharField(choices=[('B', 'Biasa'), ('P', 'Penting'), ('SP', 'Sangat Penting')], default='B', max_length=16)),
                ('destination_address', models.CharField(max_length=160, null=True)),
                ('description', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ManyToManyField(to='arsip.Department')),
                ('file', models.ManyToManyField(to='arsip.File')),
                ('jenisBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arsip.JenisBerkas')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arsip.Pengguna')),
            ],
        ),
        migrations.AddField(
            model_name='pengguna',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arsip.Role'),
        ),
    ]
