# Generated by Django 3.0.11 on 2021-09-11 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departementID', models.CharField(max_length=6)),
                ('departementName', models.CharField(max_length=21)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link_dir', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisBerkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenisCode', models.CharField(max_length=6)),
                ('jenisName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleCode', models.CharField(max_length=4)),
                ('roleName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBerkas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCode', models.CharField(max_length=3)),
                ('typeName', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=21)),
                ('password', models.TextField(max_length=21)),
                ('time_login', models.IntegerField(default=5000)),
                ('state', models.TextField(blank=True, max_length=21)),
                ('member_of', models.ManyToManyField(to='arsip.Departemen')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arsip.Role')),
            ],
        ),
        migrations.CreateModel(
            name='BerkasMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('fileName', models.CharField(default=None, max_length=120)),
                ('address_sender', models.CharField(max_length=160, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.CharField(max_length=120, null=True)),
                ('approve', models.BooleanField(default=False)),
                ('jenisBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arsip.JenisBerkas')),
                ('read_manager', models.ManyToManyField(blank=True, related_name='manager', to='arsip.Pengguna')),
                ('read_staff', models.ManyToManyField(blank=True, related_name='staff', to='arsip.Pengguna')),
                ('typeBerkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arsip.TypeBerkas')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arsip.Pengguna')),
                ('upload_for', models.ManyToManyField(to='arsip.Role')),
                ('upload_to_departement', models.ManyToManyField(to='arsip.Departemen')),
            ],
        ),
    ]
