# Generated by Django 3.0.11 on 2021-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='nik',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
