# Generated by Django 3.0.11 on 2021-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0002_auto_20210914_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratmasuk',
            name='approve_by',
        ),
        migrations.AddField(
            model_name='suratmasuk',
            name='approve_by',
            field=models.ManyToManyField(blank=True, related_name='approved', to='arsip.Pengguna'),
        ),
    ]
