# Generated by Django 3.0.11 on 2021-09-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0003_auto_20210914_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratmasuk',
            name='url',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='fileName',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
