# Generated by Django 3.0.11 on 2021-09-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0004_auto_20210915_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratkeluar',
            name='url',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
