# Generated by Django 3.0.11 on 2021-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='divisi',
            field=models.ManyToManyField(blank=True, to='app.Divisi'),
        ),
    ]
